### ISSUE TITLE
Valheim Doesn't Launch

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#1]
The game launches successfully if I verify game files (unpatch the game), but as soon as it's patched, it will not even run (i tried launching via mod launcher and via steam, both dont work.)

![image](https://user-images.githubusercontent.com/50158159/139514331-3f811b8f-76be-43f4-979c-8528c7b5aae2.png)

**Comment by ash47** [comment]
Valheim no longer crashes and fully launched, the new mod launcher release fixes this issue,
