### ISSUE TITLE
Muck (No mobs, no powerups, keybind issues)

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#2]
- Powerups are **NOT** spawning inside chests:
![image](https://user-images.githubusercontent.com/50158159/139514572-5ad5a368-8125-467e-88ec-179da690a8ed.png)

- Mobs are **NOT** spawning around the map:
![image](https://user-images.githubusercontent.com/50158159/139514587-38ef2e1f-bcbb-49d6-8370-1d2c08fa4fd5.png)

- Keybinds don't appear to work in game:
![image](https://user-images.githubusercontent.com/50158159/139514630-bbf754aa-3363-43c0-ba86-964d98237e2b.png)

**Comment by ash47** [comment]
These have been fixed and mod launcher update with patch is live and should appear for people within 15-30 minutes.
