### ISSUE TITLE
Bridge Constructor Walking Dead

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#3]
- Bridge Constructor Walking Dead is featured in the Mods section of Mod Launcher despite us having ZERO mods for the game.
![image](https://user-images.githubusercontent.com/50158159/139514732-e88f12e8-ba59-4339-965e-409c3bf253ef.png)
![image](https://user-images.githubusercontent.com/50158159/139514767-a1b8b2ea-3ae4-41e3-9bc2-a658fa2159c0.png)

**Comment by ash47** [comment]
This is only an issue with an old school mod launcher, any new installs wont have this issue.
