### ISSUE TITLE
Feed and Grow: Fish (Noclip Mod) **URGENT FIX**

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#4]
**FIX URGENTLY, ELITE YEARLY REQUESTED**
When I use the **No-CLIP** function, when I cancel, the fish will sink to the sea, and the buoyancy does not re-apply.

**Comment by ash47** [comment]
Triaged successfully. Issue is confirmed and reproducable.

**Comment by ash47** [comment]
This has been fixed, update is out.
