### ISSUE TITLE
Shark Lasers Mod (Several Fixes Needed)

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#5]
1. Shark Lasers Laser Beam is TOO DARK, especially when color is changed, and doesnt look good at all.

Currently looks like this:
![image](https://user-images.githubusercontent.com/50158159/139520625-55e7deb9-935f-4c8c-87e4-3f5aafbc4a0f.png)

Should Look like this:
![image](https://user-images.githubusercontent.com/50158159/139520629-00181b21-47a0-4d7e-aac0-a34206785c92.png)
![image](https://user-images.githubusercontent.com/50158159/139520631-09994e1d-a4ac-48b4-9a3c-ac52e6b3468e.png)

2. The angle of the laser beam should also be able to be adjusted left to right and up to down.
3. Should be able to hide the custom laser shooter model thingy.
4. Should be able to adjust laser origin (x+- Y+- Z+-)

**Comment by ash47** [comment]
Fixed most of this, laser beam could still use a little improvements but its much better than it was.
