### ISSUE TITLE
Feed and Grow Fish (No Fish Spawning in Sea)

### ISSUE THREAD

**Issue by AzzaFortysix** [AzzaMediaGroup/AzzaModsList#6]
As Above ^****

**Comment by ash47** [comment]
![image](https://user-images.githubusercontent.com/3754510/140265509-a264bb7e-3055-4041-b889-a86ba2c77a53.png)

Per screenshot, this seems fixed, if the issues persists, please be more specifc with reproduction steps, such as map, mods, etc.
